# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 20:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolBookSr', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='schedule',
            name='day_of',
            field=models.IntegerField(choices=[(1, 'Monday'), (2, 'Tuesday'), (3, 'Wednesday'), (4, 'Thursday'), (5, 'Friday')], default=1, verbose_name='Day of'),
            preserve_default=False,
        ),
    ]
