# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2016-12-13 20:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SchoolBookSr', '0002_schedule_day_of'),
    ]

    operations = [
        migrations.CreateModel(
            name='Support',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=24, verbose_name='Name')),
                ('surname', models.CharField(max_length=24, verbose_name='Surname')),
                ('title', models.CharField(max_length=54, verbose_name='Title')),
                ('description', models.CharField(max_length=1024, verbose_name='Description')),
                ('phone', models.IntegerField(verbose_name='Phone number')),
                ('grade', models.IntegerField(choices=[(1, 'Grade 1'), (2, 'Grade 2'), (3, 'Grade 3'), (4, 'Grade 4'), (5, 'Grade 5'), (6, 'Grade 6'), (7, 'Grade 7'), (8, 'Grade 8'), (9, 'Grade 9'), (10, 'Grade 10'), (11, 'Grade 11')], verbose_name='Grade')),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True, verbose_name='created_at')),
                ('updated_at', models.DateTimeField(auto_now=True, null=True, verbose_name='updated_at')),
            ],
        ),
    ]
